context:
  name: "mimick"
  version: "0.3.0"
  git_rev: "c45fa027153b4b197dae33d0dea84b4cd630ce7c"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/LucienMorey/Mimick.git
  rev: ${{ git_rev }}

build:
  number: 0
  script:
    - cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_TESTING=OFF
    - cmake --build build --parallel $CPU_COUNT
    - cmake --install build

requirements:
  build:
    - cmake
    - ninja

tests:
  - files:
      source:
        - test.c
    script:
      - test -f $PREFIX/lib/libmimick.a
      - test -f $PREFIX/include/mimick/mimick.h
      - test -f $PREFIX/lib/cmake/mimick/mimickConfig.cmake
      - gcc test.c -I$PREFIX/include -L$PREFIX/lib -lmimick -ldl -o mimick-smoke
      - ./mimick-smoke

about:
  homepage: https://github.com/LucienMorey/Mimick
  repository: https://github.com/LucienMorey/Mimick
  summary: Mocking and stubbing library for C with riscv64 support
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - trdthg
