name: Build all packages

# this is important for trusted publishing
permissions:
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - { target: linux-riscv64, os: k1 }
      fail-fast: false

    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Use pre-installed pixi now
      # - uses: prefix-dev/setup-pixi@v0.9.4
      #   with:
      #     pixi-version: v0.68.0

      - name: Run code in changed subdirectories
        shell: bash
        run: |
          rattler-build build --recipe-dir . \
            --skip-existing=all --target-platform=${{ matrix.target }}

      - name: Upload all packages
        shell: bash
        # do not upload on PR
        if: github.event_name == 'push'
        run: |
          # uses trusted publishers for the upload
          for file in output/**/*.conda; do
            if ! output=$(rattler-build upload prefix -c riscv "$file" 2>&1); then
              if grep -q "package already exists (HTTP 409)" <<< "$output"; then
                echo "Package already exists, skipping: $file"
              else
                echo "$output"
                exit 1
              fi
            fi
          done
